#!/usr/bin/env python

Import("env")

env.custom_feature_sources = []
env.add_source_files(env.custom_feature_sources, "*.cpp")
lib = env.add_library("custom_feature", env.custom_feature_sources)
env.Prepend(LIBS=[lib])